# Generated by Django 3.2.5 on 2021-08-08 07:46

from django.db import migrations, models
import modelextra.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[modelextra.models.my_age_validator]),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
