# Generated by Django 3.2.5 on 2021-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
