# Generated by Django 3.2.5 on 2021-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0003_alter_userinfo_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
